
---
dist: bionic
language: minimal

cache:
  directories:
    - /home/travis/.vagrant.d/boxes

jobs:
  include:

    - stage: build
      install:
        - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
        - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
        - sudo dpkg -i vagrant_2.2.9_x86_64.deb
        - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload
      script:
        - echo '{"semantic-release":{"user":"vagrant","bot":{"name":"Maximillian Papandrious","email":"max@example.com","token":"1048482827348451eb245144fac345d2e1514436"},"repo":"max/hello-world.git","nodejs":{"version":"12.18.4","nvm":{"version":"0.36.0"}}}}' > salt/roots/pillar/semantic-release.sls
        - travis_wait sudo vagrant up --provider=libvirt
        - travis_wait sudo vagrant ssh semantic-release-box -- sudo salt-call state.sls podman
        - travis_wait sudo vagrant ssh semantic-release-box -- sudo salt-call state.sls semantic-release.package
        - sudo vagrant destroy --force semantic-release-box

    - stage: release
      install:
        - wget https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh
        - sudo bash install.sh
        - nvm install lts/*
        - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          all_branches: true 

notifications:
  slack:
    secure: kSHwZpEsUXOAFZAHmIYzPUxdNuqreLng5QTMTKgqiTY1Z/cLBK6a7rr6hxTDeAFGKFqYMwkIFpRHvJxNF6TwYELjKyBAZcpZRssUPL6GOCi3I+acZTgqeyVSrutzQsCPjX0K/1RlLauvKRwsJFyDBV1Y/XEu5dfBpihI7QH4G2kkGteXa0T+OjxabuyRERltUX18bQM3gj7k8vTcaPWGN3PiqSbuw3tjROf1PFYeID0w0693XCBx5FiSr+bgqidRXZiN1RQjbhnlGiE4T5UyZcDXNGUycV0ZWyIK2KZNCFCXTk9fnT+x+Pl87dGFfeXRJ8brbPFNjZSfRNDuwB05g8GDKK0+TwwjhjNTrKoxPerGhf6h4bJ+d+r05u3up858HMapkBQnhTJvGFjTVtbVf+OKwpAuK+KZbeXkcVKezG7vpBnURc2L1Sk5ynwgMXwndcuRbUbrNOjHqLxnTNGsr9oZjSaW4FLRTgcz3OBYDQ7tXR14PPpTcpMVajW/RV8m0jGixcLNhnuQ++RiOa5FvLN0J16YN6jS+WzukhR6CB5A7e9XD04sOUB3MpEfC9aI+Gynm/7yTMNP9N4SCGOgAOE9fRcyyn5kZ/5Z4gf1yqAyVbcAIn6S/B3Y8A9k6Jq287GdYhV97Y6MX56gZHp2MLtf5XTfPv/vRgsiy35YD5k=
