os: Ubuntu
platform:
  - x64
install:
  - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
  - sudo dpkg -i vagrant_2.2.9_x86_64.deb
  - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload vagrant-vbguest
  - git submodule init
  - git submodule update
build_script:
  - echo '{"semantic-release":{"user":"vagrant","bot":{"name":"Maximillian Papandrious","email":"max@example.com","token":"1048482827348451eb245144fac345d2e1514436"},"repo":"max/hello-world.git","nodejs":{"version":"12.18.4","nvm":{"version":"0.36.0"}}}}' > salt/roots/pillar/semantic-release.sls
  - sudo vagrant up --provider=libvirt
  - sudo vagrant ssh semantic-release-box -- sudo salt-call state.sls podman
  - sudo vagrant ssh semantic-release-box -- sudo salt-call state.sls semantic-release.package
  - sudo vagrant destroy --force semantic-release-box
test: off
